# wrangler.toml

name               = "opspad"
compatibility_date = "2025-05-24"
workers_dev        = true
account_id         = "65e037654486897c5f9b14fba97d2b14"

[build]
command = "npm run build"

[site]
bucket = "./build"       # CRA output
entry-point = "."        # root of your project
