# wrangler.toml

name               = "opspad"
compatibility_date = "2025-05-25"
workers_dev        = true
account_id         = ""

main = "./index.js"

[build]
command = "npm run build"

# [site]
# bucket = "build"       # CRA output




