# wrangler.toml

name               = "opspad"
compatibility_date = "2025-05-25"
workers_dev        = true
account_id         = "65e037654486897c5f9b14fba97d2b14"

# main = "./index.js"

# [build]
# command = "npm run build"

# [site]
# bucket = "build"       # CRA output




