# wrangler.toml

name               = "opspad"
compatibility_date = "2025-05-24"
workers_dev        = true
account_id         = ""

main = "workers-site/index.js"

[build]
command = "npm run build"

[site]
bucket = "build"       # CRA output




